// Licenses writes resources/THIRD_PARTY_NOTICES.txt, the license files of
// every module linked into the app on any platform it ships for, of the Go
// standard library, and of the code DuckDB compiles in:
//
//	go run ./tools/licenses
//
// Run it again after changing go.mod. When duckdb-go-bindings changes
// version, first rewrite tools/licenses/duckdb.txt from the source of the
// DuckDB release it links:
//
//	go run ./tools/licenses -duckdb <DuckDB source directory>
package main

import (
	"bytes"
	"flag"
	"fmt"
	"io/fs"
	"log"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

// The platforms duckdb-go-bindings ships a library for.
var platforms = []string{"linux/amd64", "linux/arm64", "darwin/amd64", "darwin/arm64", "windows/amd64"}

var legalFile = regexp.MustCompile(`(?i)^(licen[cs]e|copying|notices?|patents|unlicense)([-._].*)?$`)

const (
	duckdbBindings = "github.com/duckdb/duckdb-go-bindings"
	duckdbFile     = "tools/licenses/duckdb.txt"
)

// DuckDB's static library holds the code of other projects, whose license
// files are in DuckDB's source but not in its Go modules. These are the
// directories of the source built into it.
var duckdbDirs = []string{
	"src", "third_party",
	"extension/autocomplete", "extension/core_functions", "extension/icu", "extension/json",
	"extension/parquet", "extension/tpcds", "extension/tpch",
}

type module struct{ path, version, dir string }

func main() {
	duckdbSource := flag.String("duckdb", "", "rewrite "+duckdbFile+" from this DuckDB source directory first")
	flag.Parse()

	modules := listModules()
	bindings, ok := modules[duckdbBindings]
	if !ok {
		log.Fatalf("%s is not linked in", duckdbBindings)
	}
	if *duckdbSource != "" {
		writeDuckDB(*duckdbSource, bindings.version)
	}
	duckdb, err := os.ReadFile(duckdbFile)
	if err != nil {
		log.Fatal(err)
	}
	duckdbVersion, duckdbLicenses, _ := bytes.Cut(duckdb, []byte("\n"))
	if string(duckdbVersion) != bindings.version {
		log.Fatalf("%s is for %s %s, but the app links %s: run go run ./tools/licenses -duckdb <source of the DuckDB release it links>",
			duckdbFile, duckdbBindings, duckdbVersion, bindings.version)
	}
	goroot, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		log.Fatal(err)
	}

	var b bytes.Buffer
	b.WriteString("DGopher includes the following third-party software. Each is\n" +
		"distributed under the license reproduced below. The source of each module\n" +
		"is available from the Go module proxy, https://proxy.golang.org, by its\n" +
		"path and version.\n" +
		"Generated by `go run ./tools/licenses`; do not edit.\n")
	writeModule(&b, module{"Go standard library", "", strings.TrimSpace(string(goroot))})
	for _, path := range slices.Sorted(maps.Keys(modules)) {
		writeModule(&b, modules[path])
	}
	writeHeading(&b, "Code compiled into DuckDB, from its source at https://github.com/duckdb/duckdb")
	b.Write(duckdbLicenses)
	if err := os.WriteFile("resources/THIRD_PARTY_NOTICES.txt", b.Bytes(), 0o644); err != nil {
		log.Fatal(err)
	}
}

// listModules returns the modules linked into the app on any of platforms,
// by path.
func listModules() map[string]module {
	modules := map[string]module{}
	for _, p := range platforms {
		goos, goarch, _ := strings.Cut(p, "/")
		cmd := exec.Command("go", "list", "-deps", "-f",
			`{{with .Module}}{{if not .Main}}{{with or .Replace .}}{{.Path}}{{"\t"}}{{.Version}}{{"\t"}}{{.Dir}}{{end}}{{end}}{{end}}`, ".")
		cmd.Env = append(os.Environ(), "GOOS="+goos, "GOARCH="+goarch, "CGO_ENABLED=1")
		cmd.Stderr = os.Stderr
		out, err := cmd.Output()
		if err != nil {
			log.Fatalf("go list for %s: %v", p, err)
		}
		for line := range strings.Lines(string(out)) {
			f := strings.Split(strings.TrimSpace(line), "\t")
			if len(f) != 3 {
				continue
			}
			if f[2] == "" {
				log.Fatalf("%s %s is not downloaded", f[0], f[1])
			}
			modules[f[0]] = module{f[0], f[1], f[2]}
		}
	}
	return modules
}

func writeModule(b *bytes.Buffer, m module) {
	entries, err := os.ReadDir(m.dir)
	if err != nil {
		log.Fatal(err)
	}
	var files []string
	for _, e := range entries {
		if !e.IsDir() && legalFile.MatchString(e.Name()) {
			files = append(files, e.Name())
		}
	}
	if len(files) == 0 {
		log.Fatalf("%s %s has no license file in %s", m.path, m.version, m.dir)
	}
	writeHeading(b, strings.TrimSpace(m.path+" "+m.version))
	for _, name := range files {
		writeFile(b, name, filepath.Join(m.dir, name))
	}
}

// writeDuckDB writes duckdbFile: the bindings version it is for, then the
// license files under duckdbDirs of the DuckDB source in dir.
func writeDuckDB(dir, bindingsVersion string) {
	var b bytes.Buffer
	b.WriteString(bindingsVersion + "\n")
	for _, d := range duckdbDirs {
		err := filepath.WalkDir(filepath.Join(dir, d), func(path string, e fs.DirEntry, err error) error {
			if err != nil || e.IsDir() || !legalFile.MatchString(e.Name()) {
				return err
			}
			name, err := filepath.Rel(dir, path)
			if err != nil {
				return err
			}
			writeFile(&b, filepath.ToSlash(name), path)
			return nil
		})
		if err != nil {
			log.Fatal(err)
		}
	}
	if err := os.WriteFile(duckdbFile, b.Bytes(), 0o644); err != nil {
		log.Fatal(err)
	}
}

func writeHeading(b *bytes.Buffer, title string) {
	rule := strings.Repeat("=", 78)
	fmt.Fprintf(b, "\n%s\n%s\n%s\n", rule, title, rule)
}

func writeFile(b *bytes.Buffer, name, path string) {
	data, err := os.ReadFile(path)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Fprintf(b, "\n--- %s ---\n\n%s\n", name, bytes.TrimSpace(data))
}
