package datamodel

import (
	"context"
	"slices"
	"strings"
	"testing"

	"dgopher/internal/db"
	"dgopher/internal/testutil"
)

// server is an engine of the integration servers, with how a test makes
// and drops a schema of its own there.
type server struct {
	cfg          db.Config
	createSchema func(string) string
	dropSchema   func(string) string
}

func servers() []server {
	return []server{
		{
			cfg:          testutil.PGConfig(),
			createSchema: func(s string) string { return `CREATE SCHEMA "` + s + `"` },
			dropSchema:   func(s string) string { return `DROP SCHEMA IF EXISTS "` + s + `" CASCADE` },
		},
		{
			cfg:          db.Config{Name: "my", Engine: db.MySQL, Host: "127.0.0.1", Port: 13306, User: "root", Password: "dbgopher", Database: "shop"},
			createSchema: func(s string) string { return "CREATE DATABASE `" + s + "`" },
			dropSchema:   func(s string) string { return "DROP DATABASE IF EXISTS `" + s + "`" },
		},
		{
			cfg:          db.Config{Name: "duck", Engine: db.DuckDB, Database: ":memory:"},
			createSchema: func(s string) string { return `CREATE SCHEMA "` + s + `"` },
			dropSchema:   func(s string) string { return `DROP SCHEMA IF EXISTS "` + s + `" CASCADE` },
		},
	}
}

// shopTables are the tables of a schema to model on each engine: a key
// with an action, a unique constraint, a check, an index and a cycle.
func shopTables(e db.Engine, s string) []string {
	q := func(name string) string { return db.QualifiedName(db.DialectOf(e), s, name) }
	id := map[db.Engine]string{db.Postgres: "integer GENERATED BY DEFAULT AS IDENTITY", db.MySQL: "int AUTO_INCREMENT", db.DuckDB: "INTEGER"}[e]
	cascade := " ON DELETE CASCADE"
	if e == db.DuckDB {
		cascade = ""
	}
	stmts := []string{
		`CREATE TABLE ` + q("customers") + ` (id ` + id + ` PRIMARY KEY, email varchar(100) NOT NULL, name varchar(50) DEFAULT 'none',
			CONSTRAINT customers_email UNIQUE (email))`,
		`CREATE TABLE ` + q("orders") + ` (id integer PRIMARY KEY, customer_id integer, total decimal(10,2) NOT NULL,
			CONSTRAINT orders_customer_fk FOREIGN KEY (customer_id) REFERENCES ` + q("customers") + ` (id)` + cascade + `,
			CONSTRAINT orders_total CHECK (total >= 0))`,
		`CREATE INDEX orders_total_ix ON ` + q("orders") + ` (total)`,
	}
	if e != db.DuckDB {
		// DuckDB adds no key to a table made, which a cycle needs.
		stmts = append(stmts,
			`CREATE TABLE `+q("a")+` (id integer PRIMARY KEY, b_id integer)`,
			`CREATE TABLE `+q("b")+` (id integer PRIMARY KEY, a_id integer, CONSTRAINT b_a FOREIGN KEY (a_id) REFERENCES `+q("a")+` (id))`,
			`ALTER TABLE `+q("a")+` ADD CONSTRAINT a_b FOREIGN KEY (b_id) REFERENCES `+q("b")+` (id)`)
	}
	return stmts
}

// A model built from each engine makes its schema again in another
// schema, alike; a migration then makes the copy like the model changed;
// and the model's script for each other engine runs there.
func TestIntegrationModels(t *testing.T) {
	testutil.Integration(t)
	ctx := context.Background()
	for _, srv := range servers() {
		t.Run(string(srv.cfg.Engine), func(t *testing.T) {
			d, err := db.Open(ctx, srv.cfg, nil)
			if err != nil {
				t.Fatal(err)
			}
			defer d.Close()
			exec := func(stmts ...string) {
				t.Helper()
				for _, s := range stmts {
					if _, err := d.SQL.ExecContext(ctx, s); err != nil {
						t.Fatalf("%s: %v", s, err)
					}
				}
			}
			for _, s := range []string{"it_model_a", "it_model_b"} {
				exec(srv.dropSchema(s), srv.createSchema(s))
				defer d.SQL.ExecContext(ctx, srv.dropSchema(s))
			}
			exec(shopTables(srv.cfg.Engine, "it_model_a")...)
			read := func(schema string) *Model {
				t.Helper()
				tables, notes, err := Build(ctx, d, schema, nil, nil)
				if err != nil || len(notes) > 0 {
					t.Fatal(err, notes)
				}
				return &Model{Name: "shop", Engine: srv.cfg.Engine, Tables: tables}
			}
			same := func(a, b *Model) {
				t.Helper()
				diffs, err := Compare(a, b)
				if err != nil {
					t.Fatal(err)
				}
				for _, df := range diffs {
					if df.State != Same {
						t.Fatalf("%s differs (%d): %+v", df.Name, df.State, df.Changes)
					}
				}
			}
			m := read("it_model_a")
			if len(m.Tables) < 2 {
				t.Fatalf("tables %+v", m.Tables)
			}
			o, _ := m.Table("it_model_a", "orders")
			// DuckDB names keys itself.
			if i := slices.IndexFunc(o.ForeignKeys, func(fk db.ForeignKeyDesign) bool { return fk.RefTable == "customers" }); i < 0 ||
				srv.cfg.Engine != db.DuckDB && o.ForeignKeys[i].OnDelete != "CASCADE" {
				t.Fatalf("keys %+v", o.ForeignKeys)
			}

			ch, notes := Script(m, srv.cfg.Engine, "it_model_b")
			if len(notes) > 0 {
				t.Fatalf("notes %q", notes)
			}
			apply(t, d, ch)
			same(m, read("it_model_b"))

			i := slices.IndexFunc(m.Tables, func(t db.TableDesign) bool { return t.Name == "orders" })
			m.Tables[i].Columns = append(m.Tables[i].Columns, db.ColumnDesign{Name: "note", Type: "varchar(20)", Nullable: true})
			m.Tables = append(m.Tables, db.TableDesign{Schema: "it_model_a", Name: "items", Columns: []db.ColumnDesign{
				{Name: "id", Type: "integer", PrimaryKey: true}, {Name: "order_id", Type: "integer", Nullable: true}},
				ForeignKeys: []db.ForeignKeyDesign{{Name: "items_order", Columns: []string{"order_id"}, RefSchema: "it_model_a", RefTable: "orders", RefColumns: []string{"id"}}}})
			ch, notes, err = Migration(m, read("it_model_b"), "it_model_b", false)
			if err != nil || len(notes) > 0 {
				t.Fatal(err, notes)
			}
			apply(t, d, ch)
			same(m, read("it_model_b"))

			for _, other := range servers() {
				if other.cfg.Engine == srv.cfg.Engine {
					continue
				}
				od, err := db.Open(ctx, other.cfg, nil)
				if err != nil {
					t.Fatal(err)
				}
				defer od.Close()
				for _, s := range []string{other.dropSchema("it_model_c"), other.createSchema("it_model_c")} {
					if _, err := od.SQL.ExecContext(ctx, s); err != nil {
						t.Fatal(s, err)
					}
				}
				ch, _ := Script(m, other.cfg.Engine, "it_model_c")
				apply(t, od, ch)
				od.SQL.ExecContext(ctx, other.dropSchema("it_model_c"))
			}

			migrate := func(to *Model, schema string, drop bool) {
				t.Helper()
				ch, notes, err := Migration(to, read(schema), schema, drop)
				if err != nil || len(notes) > 0 {
					t.Fatal(err, notes)
				}
				apply(t, d, ch)
				same(to, read(schema))
			}
			if srv.cfg.Engine != db.DuckDB {
				// A key of a new table to a unique index the migration adds.
				i := slices.IndexFunc(m.Tables, func(t db.TableDesign) bool { return t.Name == "orders" })
				m.Tables[i].Indexes = append(m.Tables[i].Indexes, db.IndexDesign{Name: "orders_note", Columns: []string{"note"}, Unique: true})
				m.Tables = append(m.Tables, db.TableDesign{Schema: "it_model_a", Name: "notes", Columns: []db.ColumnDesign{
					{Name: "id", Type: "integer", PrimaryKey: true}, {Name: "note", Type: "varchar(20)", Nullable: true}},
					ForeignKeys: []db.ForeignKeyDesign{{Name: "notes_note", Columns: []string{"note"}, RefSchema: "it_model_a", RefTable: "orders", RefColumns: []string{"note"}}}})
				migrate(m, "it_model_b", false)
			}
			// Back as it was: tables dropped that point at what else is
			// dropped, a unique index other tables' keys point at among it.
			// DuckDB drops no column of a table with an index or a key.
			if srv.cfg.Engine != db.DuckDB {
				migrate(read("it_model_a"), "it_model_b", true)
			}

			// A column a sequence numbers numbers its rows still once its
			// table changes.
			numbered := map[db.Engine][]string{
				db.Postgres: {`CREATE TABLE it_model_a.tickets (id serial PRIMARY KEY, title varchar(20))`},
				db.MySQL:    {"CREATE TABLE it_model_a.tickets (id int AUTO_INCREMENT PRIMARY KEY, title varchar(20))"},
				db.DuckDB: {`CREATE SEQUENCE it_model_a.tickets_id`,
					`CREATE TABLE it_model_a.tickets (id INTEGER PRIMARY KEY DEFAULT nextval('it_model_a.tickets_id'), title VARCHAR)`},
			}[srv.cfg.Engine]
			exec(numbered...)
			a := read("it_model_a")
			i = slices.IndexFunc(a.Tables, func(t db.TableDesign) bool { return t.Name == "tickets" })
			a.Tables[i].Columns = append(a.Tables[i].Columns, db.ColumnDesign{Name: "done", Type: "integer", Nullable: true})
			migrate(a, "it_model_a", false)
			exec(`INSERT INTO it_model_a.tickets (title) VALUES ('first')`)

			// Made new elsewhere, the table numbers its rows of itself, as
			// the notes say, where the engine can.
			ch, notes, err = Migration(a, read("it_model_b"), "it_model_b", false)
			if err != nil || srv.cfg.Engine != db.MySQL && !slices.ContainsFunc(notes, func(s string) bool { return strings.Contains(s, "identity") }) {
				t.Fatal(err, notes)
			}
			apply(t, d, ch)
			if srv.cfg.Engine != db.DuckDB {
				exec(`INSERT INTO it_model_b.tickets (title) VALUES ('first')`)
			}
			// Changed elsewhere, it keeps the sequence of its own schema.
			exec(`DROP TABLE it_model_b.tickets`)
			for _, q := range numbered {
				exec(strings.ReplaceAll(q, "it_model_a", "it_model_b"))
			}
			a.Tables[i].Columns = append(a.Tables[i].Columns, db.ColumnDesign{Name: "due", Type: "integer", Nullable: true})
			ch, notes, err = Migration(a, read("it_model_b"), "it_model_b", false)
			if err != nil || len(notes) > 0 {
				t.Fatal(err, notes)
			}
			apply(t, d, ch)
			b, _ := read("it_model_b").Table("it_model_b", "tickets")
			if len(b.Columns) != 4 {
				t.Fatalf("tickets %+v", b.Columns)
			}
			if strings.Contains(b.Columns[0].Default, "it_model_a") {
				t.Fatalf("it_model_b.tickets numbered by %s", b.Columns[0].Default)
			}
			exec(`INSERT INTO it_model_b.tickets (title) VALUES ('first')`)
		})
	}
}
