package sqltext

import (
	"sort"
	"strings"
)

const standardKeywords = `ADD ALL ALTER ANALYZE AND ANY AS ASC BEGIN BETWEEN BIGINT BINARY BOOLEAN BOTH BY CALL CASCADE
CASE CAST CHAR CHARACTER CHECK COLLATE COLUMN COMMENT COMMIT CONSTRAINT CREATE CROSS CURRENT_DATE
CURRENT_TIME CURRENT_TIMESTAMP DATABASE DATE DECIMAL DECLARE DEFAULT DELETE DESC DESCRIBE DISTINCT
DOUBLE DROP ELSE END ESCAPE EXCEPT EXECUTE EXISTS EXPLAIN FALSE FETCH FIRST FLOAT FOR FOREIGN FROM
FULL FUNCTION GRANT GROUP HAVING IF IN INDEX INNER INSERT INT INTEGER INTERSECT INTERVAL INTO IS JOIN
KEY LEADING LEFT LIKE LIMIT LOCK MERGE NATURAL NOT NULL NUMERIC OFFSET ON OR ORDER OUTER OVER
PARTITION PRECISION PRIMARY PROCEDURE REAL RECURSIVE REFERENCES RELEASE RENAME REPLACE RESET RETURNS
REVOKE RIGHT ROLLBACK ROW ROWS SAVEPOINT SCHEMA SELECT SET SHOW SMALLINT START TABLE TEMPORARY THEN
TIME TIMESTAMP TO TRAILING TRANSACTION TRIGGER TRUE TRUNCATE UNION UNIQUE UPDATE USE USING VALUES
VARCHAR VIEW WHEN WHERE WINDOW WITH WITHOUT NULLS LAST FILTER QUALIFY`

const postgresKeywords = `ABORT ANALYSE ARRAY ASYMMETRIC CLUSTER CONCURRENTLY CONFLICT COPY DEALLOCATE DISCARD DO
EXCLUDE ILIKE JSONB LATERAL LISTEN MATERIALIZED NOTHING NOTIFY NOWAIT ONLY OWNER PREPARE REFRESH
REINDEX RETURNING SEQUENCE SERIAL SIMILAR SYMMETRIC TABLESAMPLE TEXT UNLISTEN UUID VACUUM VERBOSE POSITIONAL`

const mysqlKeywords = `AUTO_INCREMENT CHARSET DATABASES DEALLOCATE DO DUAL DUMPFILE DUPLICATE ENGINE ENGINES
FORCE HANDLER IGNORE INFILE KILL LOAD LOW_PRIORITY OPTIMIZE OUTFILE PREPARE PROCESSLIST REGEXP
SHOW STRAIGHT_JOIN TABLES TEXT TINYINT UNSIGNED UPSERT ZEROFILL`

const clickhouseKeywords = `ARRAY ATTACH CLUSTER CODEC DETACH DICTIONARY ENGINE EXCHANGE FINAL FORMAT GLOBAL
ILIKE KILL LIVE MATERIALIZED OPTIMIZE PREWHERE SAMPLE SETTINGS SYSTEM TABLES TTL UNDROP SEMI ANTI ASOF PASTE`

var keywordSets = map[Dialect]map[string]bool{}

func init() {
	extra := map[Dialect]string{Generic: "", Postgres: postgresKeywords, MySQL: mysqlKeywords, ClickHouse: clickhouseKeywords, SQLite: "GLOB PRAGMA"}
	for d, words := range extra {
		set := map[string]bool{}
		for _, w := range strings.Fields(standardKeywords + " " + words) {
			set[w] = true
		}
		keywordSets[d] = set
	}
}

func keywordSet(d Dialect) map[string]bool {
	if s, ok := keywordSets[d]; ok {
		return s
	}
	return keywordSets[Generic]
}

// Keywords returns the sorted upper-case keyword list for the dialect.
func Keywords(d Dialect) []string {
	set := keywordSet(d)
	out := make([]string, 0, len(set))
	for w := range set {
		out = append(out, w)
	}
	sort.Strings(out)
	return out
}
